#Dependencies

In [1]:
import pandas as pd

#Spotify's Top 100 2017 Dataset

In [2]:
#Import Spotify DB
spotify_df=pd.read_csv("Resources/featuresdf.csv", encoding="utf-8")
spotify_df.head()

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.5810,0.000000,0.0931,0.931,95.977,233713.0,4.0
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.2290,0.000000,0.0924,0.813,88.931,228827.0,4.0
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.2090,0.000000,0.1120,0.846,177.833,228200.0,4.0
3,6RUKPb4LETWmmr3iAEQkt,Something Just Like This,The Chainsmokers,0.617,0.635,11.0,-6.769,0.0,0.0317,0.0498,0.000014,0.1640,0.446,103.019,247160.0,4.0
4,3DXncPQOG4VBw3QHh3S81,I'm the One,DJ Khaled,0.609,0.668,7.0,-4.284,1.0,0.0367,0.0552,0.000000,0.1670,0.811,80.924,288600.0,4.0

#MTV's Top Music Artists Dataset (w/Facebook, Twitter, and Website info)

In [3]:
#Import media DB
social_df=pd.read_csv("Resources/Artist_socialmedia.csv", encoding="utf-8")
social_df.head()

,name,facebook,twitter,website,genre,mtv,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,name.1
0,Adele,http://www.facebook.com/9770929278,http://www.twitter.com/officialadele,NaN,Pop,http://www.mtv.com/artists/adele/biography,NaN,NaN,NaN,NaN,Adele
1,Joey + Rory,http://www.facebook.com/15044507815,http://www.twitter.com/joeyandrory,NaN,Country,http://www.cmt.com/artists/joey-rory/biography,NaN,NaN,NaN,NaN,Joey + Rory
2,Draaco Aventura,http://www.facebook.com/856796091053581,http://www.twitter.com/DraacoAventura,http://www.bandpage.com/draacoaventura,Pop Latino,http://www.mtv.com/artists/draaco-aventura/bio...,NaN,NaN,NaN,NaN,Draaco Aventura
3,Justin Bieber,http://www.facebook.com/309570926875,http://www.twitter.com/justinbieber,http://www.justinbiebermusic.com,Pop,http://www.mtv.com/artists/justin-bieber/biogr...,NaN,NaN,NaN,NaN,Justin Bieber
4,Peer van Mladen,http://www.facebook.com/264487966,http://www.twitter.com/Predrag_Jugovic,http://pejaintergroup.eu/Peer_van_Mladen.html,House,http://www.mtv.com/artists/peer-van-mladen/bio...,NaN,NaN,NaN,NaN,Peer van Mladen

#Data cleanup

In [4]:
#Clean up social media df including facebook, twitter, and website info with artist name. Rename "name" to "artists" 
#to match Spotify df
new_social_df = social_df[["name","facebook","twitter","website"]].copy()
new_social_df=new_social_df.rename(columns={"name":"artists"})
new_social_df.head()

,artists,facebook,twitter,website
0,Adele,http://www.facebook.com/9770929278,http://www.twitter.com/officialadele,NaN
1,Joey + Rory,http://www.facebook.com/15044507815,http://www.twitter.com/joeyandrory,NaN
2,Draaco Aventura,http://www.facebook.com/856796091053581,http://www.twitter.com/DraacoAventura,http://www.bandpage.com/draacoaventura
3,Justin Bieber,http://www.facebook.com/309570926875,http://www.twitter.com/justinbieber,http://www.justinbiebermusic.com
4,Peer van Mladen,http://www.facebook.com/264487966,http://www.twitter.com/Predrag_Jugovic,http://pejaintergroup.eu/Peer_van_Mladen.html

In [5]:
#Reduce Spotify df including Spotify song_id, song name, and artist. Rename "id" to "Spotify_id" to better indentify column
new_spotify_df = spotify_df[['id', 'name', 'artists']].copy()
new_spotify_df=new_spotify_df.rename(columns={"id":"Spotify_id"})
new_spotify_df.head()

              Spotify_id                                name           artists
0  7qiZfU4dY1lWllzX7mPBI                        Shape of You        Ed Sheeran
1  5CtI0qwDJkDQGwXD1H1cL                   Despacito - Remix        Luis Fonsi
2  4aWmUDTfIPGksMNLV2rQP  Despacito (Featuring Daddy Yankee)        Luis Fonsi
3  6RUKPb4LETWmmr3iAEQkt            Something Just Like This  The Chainsmokers
4  3DXncPQOG4VBw3QHh3S81                         I'm the One         DJ Khaled

In [6]:
#Drop Duplicates in Spotify DB
spotify_drop = new_spotify_df.drop_duplicates('artists')
spotify_drop.head()

              Spotify_id                      name           artists
0  7qiZfU4dY1lWllzX7mPBI              Shape of You        Ed Sheeran
1  5CtI0qwDJkDQGwXD1H1cL         Despacito - Remix        Luis Fonsi
3  6RUKPb4LETWmmr3iAEQkt  Something Just Like This  The Chainsmokers
4  3DXncPQOG4VBw3QHh3S81               I'm the One         DJ Khaled
5  7KXjTSCq5nL1LoYtL7XAw                   HUMBLE.    Kendrick Lamar

In [7]:
#Merge the two reduced df's. Change order or columns for better reading
merged_df = pd.merge(spotify_drop, new_social_df, on="artists",how="left")
merged_df = merged_df[["artists", "name", "Spotify_id", "website", "facebook", "twitter"]]
merged_df.head()

,artists,name,Spotify_id,website,facebook,twitter
0,Ed Sheeran,Shape of You,7qiZfU4dY1lWllzX7mPBI,http://www.edsheeran.com/,http://www.facebook.com/9189674485,http://www.twitter.com/edsheeran
1,Luis Fonsi,Despacito - Remix,5CtI0qwDJkDQGwXD1H1cL,NaN,NaN,NaN
2,The Chainsmokers,Something Just Like This,6RUKPb4LETWmmr3iAEQkt,http://www.thechainsmokers.com,http://www.facebook.com/198933856805679,http://www.twitter.com/thechainsmokers
3,DJ Khaled,I'm the One,3DXncPQOG4VBw3QHh3S81,NaN,http://www.facebook.com/605083229565089,http://www.twitter.com/djkhaled
4,Kendrick Lamar,HUMBLE.,7KXjTSCq5nL1LoYtL7XAw,http://www.topdawgmusic.com,http://www.facebook.com/241273033091,http://www.twitter.com/kendricklamar

MongoDB

In [8]:
import pymongo

In [9]:
#Establish connection
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [12]:
#Create schema
musicDB = client["musicDataBase"]
#Drop artist collection
musicDB.artists.drop()
#Create collection
artist_col = musicDB["artists"]

In [13]:
#Insert records into collection "artists"
xds = artist_col.insert_many(merged_df.to_dict('records'))
print(xds.inserted_ids)

[ObjectId('5cb1ffdee86ae32f14adb6be'), ObjectId('5cb1ffdee86ae32f14adb6bf'), ObjectId('5cb1ffdee86ae32f14adb6c0'), ObjectId('5cb1ffdee86ae32f14adb6c1'), ObjectId('5cb1ffdee86ae32f14adb6c2'), ObjectId('5cb1ffdee86ae32f14adb6c3'), ObjectId('5cb1ffdee86ae32f14adb6c4'), ObjectId('5cb1ffdee86ae32f14adb6c5'), ObjectId('5cb1ffdee86ae32f14adb6c6'), ObjectId('5cb1ffdee86ae32f14adb6c7'), ObjectId('5cb1ffdee86ae32f14adb6c8'), ObjectId('5cb1ffdee86ae32f14adb6c9'), ObjectId('5cb1ffdee86ae32f14adb6ca'), ObjectId('5cb1ffdee86ae32f14adb6cb'), ObjectId('5cb1ffdee86ae32f14adb6cc'), ObjectId('5cb1ffdee86ae32f14adb6cd'), ObjectId('5cb1ffdee86ae32f14adb6ce'), ObjectId('5cb1ffdee86ae32f14adb6cf'), ObjectId('5cb1ffdee86ae32f14adb6d0'), ObjectId('5cb1ffdee86ae32f14adb6d1'), ObjectId('5cb1ffdee86ae32f14adb6d2'), ObjectId('5cb1ffdee86ae32f14adb6d3'), ObjectId('5cb1ffdee86ae32f14adb6d4'), ObjectId('5cb1ffdee86ae32f14adb6d5'), ObjectId('5cb1ffdee86ae32f14adb6d6'), ObjectId('5cb1ffdee86ae32f14adb6d7'), ObjectId('5cb1ffdee86ae32f14adb6d8'), ObjectId('5cb1ffdee86ae32f14adb6d9'), ObjectId('5cb1ffdee86ae32f14adb6da'), ObjectId('5cb1ffdee86ae32f14adb6db'), ObjectId('5cb1ffdee86ae32f14adb6dc'), ObjectId('5cb1ffdee86ae32f14adb6dd'), ObjectId('5cb1ffdee86ae32f14adb6de'), ObjectId('5cb1ffdee86ae32f14adb6df'), ObjectId('5cb1ffdee86ae32f14adb6e0'), ObjectId('5cb1ffdee86ae32f14adb6e1'), ObjectId('5cb1ffdee86ae32f14adb6e2'), ObjectId('5cb1ffdee86ae32f14adb6e3'), ObjectId('5cb1ffdee86ae32f14adb6e4'), ObjectId('5cb1ffdee86ae32f14adb6e5'), ObjectId('5cb1ffdee86ae32f14adb6e6'), ObjectId('5cb1ffdee86ae32f14adb6e7'), ObjectId('5cb1ffdee86ae32f14adb6e8'), ObjectId('5cb1ffdee86ae32f14adb6e9'), ObjectId('5cb1ffdee86ae32f14adb6ea'), ObjectId('5cb1ffdee86ae32f14adb6eb'), ObjectId('5cb1ffdee86ae32f14adb6ec'), ObjectId('5cb1ffdee86ae32f14adb6ed'), ObjectId('5cb1ffdee86ae32f14adb6ee'), ObjectId('5cb1ffdee86ae32f14adb6ef'), ObjectId('5cb1ffdee86ae32f14adb6f0'), ObjectId('5cb1ffdee86ae32f14adb6f1'), ObjectId('5cb1ffdee86ae32f14adb6f2'), ObjectId('5cb1ffdee86ae32f14adb6f3'), ObjectId('5cb1ffdee86ae32f14adb6f4'), ObjectId('5cb1ffdee86ae32f14adb6f5'), ObjectId('5cb1ffdee86ae32f14adb6f6'), ObjectId('5cb1ffdee86ae32f14adb6f7'), ObjectId('5cb1ffdee86ae32f14adb6f8'), ObjectId('5cb1ffdee86ae32f14adb6f9'), ObjectId('5cb1ffdee86ae32f14adb6fa'), ObjectId('5cb1ffdee86ae32f14adb6fb'), ObjectId('5cb1ffdee86ae32f14adb6fc'), ObjectId('5cb1ffdee86ae32f14adb6fd'), ObjectId('5cb1ffdee86ae32f14adb6fe'), ObjectId('5cb1ffdee86ae32f14adb6ff'), ObjectId('5cb1ffdee86ae32f14adb700'), ObjectId('5cb1ffdee86ae32f14adb701'), ObjectId('5cb1ffdee86ae32f14adb702'), ObjectId('5cb1ffdee86ae32f14adb703'), ObjectId('5cb1ffdee86ae32f14adb704'), ObjectId('5cb1ffdee86ae32f14adb705'), ObjectId('5cb1ffdee86ae32f14adb706'), ObjectId('5cb1ffdee86ae32f14adb707'), ObjectId('5cb1ffdee86ae32f14adb708'), ObjectId('5cb1ffdee86ae32f14adb709'), ObjectId('5cb1ffdee86ae32f14adb70a'), ObjectId('5cb1ffdee86ae32f14adb70b')]